spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

  #配置数据库连接地址  #配置数据库驱动 #配置数据库用户名  #配置数据库密码
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: sa
  # ===================================================================
  # DB properties.
  # ===================================================================
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/sba?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      minimum-idle: 2
      maximum-pool-size: 10


server:
  port: 8090

    # ===================================================================
  #  properties.
  # ===================================================================
sba:
  frontend:
    url: http://localhost:4200
